### ISSUE TITLE
Reloading the LFOD campaign after a Save & Quit doesn't respect the last active checkpoint

### ISSUE THREAD

**Issue by RaceProUK** [agilbert1412/DLCQuestipelago#4]
The following assumes the Checkpoints Pack has been purchased.

In the vanilla LFOD campaign, when saving, quitting, and reloading, the game spawns the player at the last activated checkpoint. However, this behaviour is not maintained by the plugin because the `DLCManager.IsPurchased` method is patched by replacing the vanilla implementation with one entirely defined by the plugin. This then results in the player always spawning at the default location instead of the last activated checkpoint as the game believes the Checkpoints Pack has not been purchased.

**Comment by agilbert1412** [comment]
Fixed in 3.0.5
